/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit
         * @description Return the calling tenant's most recent audit rows + its total turn count.
         */
        get: operations["audit_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Case Id */
            case_id: string;
            /**
             * Document Verdict
             * @enum {string}
             */
            document_verdict: "pass" | "block" | "requires_human_review";
            /** Document Reason */
            document_reason: string | null;
            /** N Segments Total */
            n_segments_total: number;
            /** N Segments Pass */
            n_segments_pass: number;
            /** N Segments Block */
            n_segments_block: number;
            /** N Segments Review */
            n_segments_review: number;
            /** N Segments Blocked By Injection */
            n_segments_blocked_by_injection: number;
            /** Sanitizer Log */
            sanitizer_log: components["schemas"]["SanitizerEventDTO"][];
            /** Segments */
            segments: components["schemas"]["SegmentResultDTO"][];
            /** Latency Ms Total */
            latency_ms_total: number;
            /** Cost Eur Total */
            cost_eur_total: number;
            /** Response Time Ms */
            response_time_ms: number;
            pii_summary?: components["schemas"]["PIISummaryDTO"] | null;
        };
        /** AnswerDTO */
        AnswerDTO: {
            /** Text */
            text: string;
            /** Findings */
            findings: components["schemas"]["FindingDTO"][];
        };
        /**
         * AskRequest
         * @description Body for POST /ask.
         *
         *     Mutable (no frozen=True) because FastAPI mutates request models during
         *     validation. Response/data DTOs are frozen.
         */
        AskRequest: {
            /** Query */
            query: string;
            /**
             * Corpus
             * @enum {string}
             */
            corpus: "ai_act" | "gdpr" | "nis2" | "dora" | "dora_rts_incident" | "dora_rts_class" | "amlr" | "mica" | "tfr" | "auto";
            /**
             * Language
             * @enum {string}
             */
            language: "es" | "en";
            /** Council */
            council?: boolean | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Case Id */
            case_id: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "pass" | "block" | "requires_human_review";
            answer: components["schemas"]["AnswerDTO"];
            /** Audit Results */
            audit_results: components["schemas"]["AuditResultDTO"][];
            /** Reason */
            reason: string | null;
            /** Response Time Ms */
            response_time_ms: number;
            /** Council Notice */
            council_notice?: string | null;
            council?: components["schemas"]["CouncilReviewDTO"] | null;
        };
        /**
         * AuditEntryDTO
         * @description One audit-trail row (Fase 6B; ADR-0041). Hashes + metadata only — the raw
         *     query is never stored, so it is never returned (only its SHA-256).
         */
        AuditEntryDTO: {
            /** Ts */
            ts: string;
            /** Case Id */
            case_id: string;
            /** Mode */
            mode: string;
            /** Corpus */
            corpus?: string | null;
            /** Language */
            language?: string | null;
            /** Verdict */
            verdict?: string | null;
            /** Query Sha256 */
            query_sha256?: string | null;
            /** N Findings */
            n_findings?: number | null;
            /** N Citations */
            n_citations?: number | null;
            /** N Validated */
            n_validated?: number | null;
            /** N Segments */
            n_segments?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Cost Eur */
            cost_eur?: number | null;
        };
        /**
         * AuditLogResponse
         * @description The authenticated tenant's OWN audit trail (never another tenant's).
         */
        AuditLogResponse: {
            /** Enabled */
            enabled: boolean;
            /** Total */
            total: number;
            /** Entries */
            entries: components["schemas"]["AuditEntryDTO"][];
        };
        /**
         * AuditResultDTO
         * @description Subset of AuditResult: validated + 3 sub-flags + reason. No internal Citation echo.
         */
        AuditResultDTO: {
            citation: components["schemas"]["CitationDTO"];
            /** Validated */
            validated: boolean;
            /** Article Exists */
            article_exists: boolean;
            /** Apartado Exists */
            apartado_exists: boolean | null;
            /** Text Normalized Match */
            text_normalized_match: boolean;
            /** Reason */
            reason: string | null;
        };
        /** Body_analyze_analyze_post */
        Body_analyze_analyze_post: {
            /** File */
            file: string;
            /** Corpus */
            corpus: string[];
            /** Language */
            language: string;
        };
        /** CitationDTO */
        CitationDTO: {
            /** Norma */
            norma: string;
            /** Articulo */
            articulo: string;
            /** Apartado */
            apartado: string | null;
            /** Language */
            language: string;
            /** Text */
            text: string;
        };
        /** CouncilReviewDTO */
        CouncilReviewDTO: {
            /** Triggered */
            triggered: boolean;
            /**
             * Trigger Reason
             * @enum {string}
             */
            trigger_reason: "auditor_rhr" | "high_severity" | "api_override" | "not_triggered";
            /** Judges */
            judges: components["schemas"]["JudgeVoteDTO"][];
            /**
             * Council Verdict
             * @enum {string}
             */
            council_verdict: "pass" | "block" | "requires_human_review";
            /**
             * Agreement
             * @enum {string}
             */
            agreement: "unanimous" | "majority" | "split" | "degraded";
            /** Diverges From Auditor */
            diverges_from_auditor: boolean;
            /** Reason */
            reason: string;
        };
        /** FindingDTO */
        FindingDTO: {
            /** Text */
            text: string;
            /** Citations */
            citations: components["schemas"]["CitationDTO"][];
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "low" | "medium" | "high";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "present" | "missing" | "unreachable" | "degraded";
            /** Detail */
            detail: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Checks */
            checks: components["schemas"]["HealthCheck"][];
        };
        /** JudgeVoteDTO */
        JudgeVoteDTO: {
            /** Model Id */
            model_id: string;
            /** Provider */
            provider: string;
            /**
             * Vote
             * @enum {string}
             */
            vote: "pass" | "block" | "requires_human_review";
            /** Reason */
            reason: string;
            /** Ok */
            ok: boolean;
            /** Error Category */
            error_category: string | null;
        };
        /**
         * PIISummaryDTO
         * @description Advisory PII signal exposed on /analyze. Counts + kinds only — never raw
         *     values (§18.8). Surfaced to the authenticated client as a warning, like the
         *     UI banner; the document is analyzed regardless (§18.5).
         */
        PIISummaryDTO: {
            /** Total */
            total: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
        };
        /**
         * SanitizerEventDTO
         * @description Subset of SanitizerEvent. Excludes location and raw reason (SSDLC redaction).
         */
        SanitizerEventDTO: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /**
             * Category
             * @enum {string}
             */
            category: "metadata_stripped" | "annotation_stripped" | "invisible_text_stripped" | "javascript_blocked" | "attachment_blocked" | "form_action_blocked" | "uri_action_blocked" | "hidden_layer_stripped" | "unicode_trick_stripped" | "encrypted_with_password" | "outline_extracted" | "large_document_warning";
            /** Content Hash */
            content_hash: string;
        };
        /** SegmentResultDTO */
        SegmentResultDTO: {
            /** Segment Id */
            segment_id: number;
            /** Title */
            title: string | null;
            /** Skipped */
            skipped: boolean;
            /**
             * Skip Category
             * @enum {string}
             */
            skip_category: "clean" | "injection_blocked" | "internal_error";
            answer: components["schemas"]["AnswerDTO"] | null;
            /** Verdict */
            verdict: ("pass" | "block" | "requires_human_review") | null;
            /** Audit Results */
            audit_results: components["schemas"]["AuditResultDTO"][];
            /** Latency Ms */
            latency_ms: number;
            /** Cost Eur */
            cost_eur: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ask_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
